version: '3.1'
services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: website
    restart: always
    ports:
      - 80:80
    stdin_open: true
    tty: true